(function() {
    'use strict';

    window.countryList = {
        ru: {
            name: 'Россия',
            code: 'ru',
            price: 2390,
            oldPrice: 4790,
            labelPrice: 'руб.',
            phoneHelper: 'Например +7 9031234567',
            nameHelper: 'Екатерина Самойлова',
            nameError: 'Имя обязательно для заполнения',
            phoneError: 'Телефон обязателен для заполнения',
            countryError: 'Страна обязательна для заполнения',
            emailError: 'E-mail incorrect',
            emailSuccess: 'Thanks, e-mail sended',
            isDefault: true
        },
        at: {
            name: 'Австрия',
            code: 'at',
            price: 39,
            oldPrice: 78,
            labelPrice: 'евро',
            phoneHelper: 'Например +43 123456789',
            nameHelper: 'Анна Мишкина',
            nameError: 'Имя обязательно для заполнения',
            phoneError: 'Телефон обязателен для заполнения',
            emailError: 'E-mail incorrect',
            emailSuccess: 'Thanks, e-mail sended',
            countryError: 'Страна обязательна для заполнения'
        },
        az: {
            name: 'Азербайджан',
            code: 'az',
            price: 39,
            oldPrice: 79,
            labelPrice: 'манат',
            phoneHelper: 'Например +994 123456789',
            nameHelper: 'Захра Мамедова',
            nameError: 'Имя обязательно для заполнения',
            phoneError: 'Телефон обязателен для заполнения',
            emailError: 'E-mail incorrect',
            emailSuccess: 'Thanks, e-mail sended',
            countryError: 'Страна обязательна для заполнения'
        },
        am: {
            name: 'Армения',
            code: 'am',
            price: 19000,
            oldPrice: 38000,
            labelPrice: 'дрм',
            phoneHelper: 'Например +374 12345678',
            nameHelper: 'Мари Абитян',
            nameError: 'Имя обязательно для заполнения',
            phoneError: 'Телефон обязателен для заполнения',
            emailError: 'E-mail incorrect',
            emailSuccess: 'Thanks, e-mail sended',
            countryError: 'Страна обязательна для заполнения'
        },
        by: {
            name: 'Беларусь',
            code: 'by',
            price: 49,
            oldPrice: 99,
            labelPrice: 'руб.',
            phoneHelper: 'Например +375 123456789',
            nameHelper: 'Маргарыта Концява',
            nameError: 'Імя абавязковы для запаўнення',
            phoneError: 'Тэлефон абавязковы для запаўнення',
            emailError: 'E-mail incorrect',
            emailSuccess: 'Thanks, e-mail sended',
            countryError: 'Краіна абавязковы для запаўнення'
        },
        be: {
            name: 'Бельгия',
            code: 'be',
            price: 39,
            oldPrice: 78,
            labelPrice: 'евро',
            phoneHelper: 'Например +32 1234567890',
            nameHelper: 'Екатерина Самойлова',
            nameError: 'Имя обязательно для заполнения',
            phoneError: 'Телефон обязателен для заполнения',
            countryError: 'Страна обязательна для заполнения',
            emailError: 'E-mail incorrect',
            emailSuccess: 'Thanks, e-mail sended',
        },
        bg: {
            name: 'Болгария',
            code: 'bg',
            price: 59,
            oldPrice: 118,
            labelPrice: 'лев',
            phoneHelper: 'Например +359 12345678',
            nameHelper: 'Мария Агова',
            nameError: 'Имя обязательно для заполнения',
            phoneError: 'Телефон обязателен для заполнения',
            emailError: 'E-mail incorrect',
            emailSuccess: 'Thanks, e-mail sended',
            countryError: 'Страна обязательна для заполнения'
        },
		gb: {
            name: 'Великобритания',
            code: 'gb',
            price: 39,
            oldPrice: 78,
            labelPrice: 'фунт',
            phoneHelper: 'Например +44 123456789',
            nameHelper: 'Екатерина Самойлова',
            nameError: 'Имя обязательно для заполнения',
            phoneError: 'Телефон обязателен для заполнения',
            emailError: 'E-mail incorrect',
            emailSuccess: 'Thanks, e-mail sended',
            countryError: 'Страна обязательна для заполнения'
        },
        hu: {
            name: 'Венгрия',
            code: 'hu',
            price: 8900,
            oldPrice: 17800,
            labelPrice: 'фор',
            phoneHelper: 'Например +36 12345678',
            nameHelper: 'Екатерина Самойлова',
            nameError: 'Имя обязательно для заполнения',
            phoneError: 'Телефон обязателен для заполнения',
            emailError: 'E-mail incorrect',
            emailSuccess: 'Thanks, e-mail sended',
            countryError: 'Страна обязательна для заполнения'
        },
        de: {
            name: 'Германия',
            code: 'de',
            price: 39,
            oldPrice: 78,
            labelPrice: 'евро',
            phoneHelper: 'Например +490 123456789',
            nameHelper: 'Ханна Беккер',
            nameError: 'Имя обязательно для заполнения',
            phoneError: 'Телефон обязателен для заполнения',
            emailError: 'E-mail incorrect',
            emailSuccess: 'Thanks, e-mail sended',
            countryError: 'Страна обязательна для заполнения'
        },
        gr: {
            name: 'Греция',
            code: 'gr',
            price: 29,
            oldPrice: 58,
            labelPrice: 'евро',
            phoneHelper: 'Например +30 0123456789',
            nameHelper: 'Екатерина Самойлова',
            nameError: 'Имя обязательно для заполнения',
            phoneError: 'Телефон обязателен для заполнения',
            emailError: 'E-mail incorrect',
            emailSuccess: 'Thanks, e-mail sended',
            countryError: 'Страна обязательна для заполнения'
        },
        es: {
            name: 'Испания',
            code: 'es',
            price: 39,
            oldPrice: 78,
            labelPrice: 'евро',
            phoneHelper: 'Например +34 123456789',
            nameHelper: 'Анна Мишкина',
            nameError: 'Имя обязательно для заполнения',
            phoneError: 'Телефон обязателен для заполнения',
            emailError: 'E-mail incorrect',
            emailSuccess: 'Thanks, e-mail sended',
            countryError: 'Страна обязательна для заполнения'
        },
        it: {
            name: 'Италия',
            code: 'it',
            price: 39,
            oldPrice: 78,
            labelPrice: 'евро',
            phoneHelper: 'Например +39 1234567890',
            nameHelper: 'Екатерина Самойлова',
            nameError: 'Имя обязательно для заполнения',
            phoneError: 'Телефон обязателен для заполнения',
            emailError: 'E-mail incorrect',
            emailSuccess: 'Thanks, e-mail sended',
            countryError: 'Страна обязательна для заполнения'
        },
        kz: {
            name: 'Казахстан',
            code: 'kz',
            price: 6100,
            oldPrice: 12200,
            labelPrice: 'тг.',
            phoneHelper: 'Например +77 123456789',
            nameHelper: 'Айжаксым Омарова',
            nameError: 'Имя обязательно для заполнения',
            phoneError: 'Телефон обязателен для заполнения',
            emailError: 'E-mail incorrect',
            emailSuccess: 'Thanks, e-mail sended',
            countryError: 'Страна обязательна для заполнения'
        },
        cy: {
            name: 'Кипр',
            code: 'cy',
            price: 29,
            oldPrice: 58,
            labelPrice: 'евро',
            phoneHelper: 'Например +357 12345678',
            nameHelper: 'Екатерина Самойлова',
            nameError: 'Имя обязательно для заполнения',
            phoneError: 'Телефон обязателен для заполнения',
            emailError: 'E-mail incorrect',
            emailSuccess: 'Thanks, e-mail sended',
            countryError: 'Страна обязательна для заполнения'
        },
        kg: {
            name: 'Киргизия',
            code: 'kg',
            price: 1990,
            oldPrice: 3990,
            labelPrice: 'сом',
            phoneHelper: 'Например +996 123456789',
            nameHelper: 'Жазгуль Кирдякова',
            nameError: 'Имя обязательно для заполнения',
            phoneError: 'Телефон обязателен для заполнения',
            emailError: 'E-mail incorrect',
            emailSuccess: 'Thanks, e-mail sended',
            countryError: 'Страна обязательна для заполнения'
        },
        lv: {
            name: 'Латвия',
            code: 'lv',
            price: 39,
            oldPrice: 78,
            labelPrice: 'евро',
            phoneHelper: 'Например +371 12345678',
            nameHelper: 'Санита Берзиньш',
            nameError: 'Имя обязательно для заполнения',
            phoneError: 'Телефон обязателен для заполнения',
            emailError: 'E-mail incorrect',
            emailSuccess: 'Thanks, e-mail sended',
            countryError: 'Страна обязательна для заполнения'
        },
        lt: {
            name: 'Литва',
            code: 'lt',
            price: 39,
            oldPrice: 78,
            labelPrice: 'евро',
            phoneHelper: 'Например +370 12345678',
            nameHelper: 'Лайма Дауканте',
            nameError: 'Имя обязательно для заполнения',
            phoneError: 'Телефон обязателен для заполнения',
            emailError: 'E-mail incorrect',
            emailSuccess: 'Thanks, e-mail sended',
            countryError: 'Страна обязательна для заполнения'
        },
        lu: {
            name: 'Люксембург',
            code: 'lu',
            price: 39,
            oldPrice: 78,
            labelPrice: 'евро',
            phoneHelper: 'Например +352 123456789',
            nameHelper: 'Лайма Дауканте',
            nameError: 'Имя обязательно для заполнения',
            phoneError: 'Телефон обязателен для заполнения',
            emailError: 'E-mail incorrect',
            emailSuccess: 'Thanks, e-mail sended',
            countryError: 'Страна обязательна для заполнения'
        },
        mk: {
            name: 'Македония',
            code: 'mk',
            price: 1990,
            oldPrice: 3990,
            labelPrice: 'денар',
            phoneHelper: 'Например +389 123456789',
            nameHelper: 'Elena Ionescu',
            nameError: 'Имя обязательно для заполнения',
            phoneError: 'Телефон обязателен для заполнения',
            emailError: 'E-mail incorrect',
            emailSuccess: 'Thanks, e-mail sended',
            countryError: 'Страна обязательна для заполнения'
        },
        md: {
            name: 'Молдавия',
            code: 'md',
            price: 600,
            oldPrice: 1198,
            labelPrice: 'лей',
            phoneHelper: 'Например +373 12345678',
            nameHelper: 'Elena Ionescu',
            nameError: 'Numele dorit pentru a umple',
            phoneError: 'Telefon necesare pentru a umple',
            emailError: 'E-mail incorrect',
            emailSuccess: 'Thanks, e-mail sended',
            countryError: 'Țara este necesară pentru a umple'
        },
		nl: {
            name: 'Нидерланды',
            code: 'nl',
            price: 39,
            oldPrice: 78,
            labelPrice: 'евро',
            phoneHelper: 'Например +31 123456789',
            nameHelper: 'Екатерина Самойлова',
            nameError: 'Имя обязательно для заполнения',
            phoneError: 'Телефон обязателен для заполнения',
            emailError: 'E-mail incorrect',
            emailSuccess: 'Thanks, e-mail sended',
            countryError: 'Страна обязательна для заполнения'
        },
        no: {
            name: 'Норвегия',
            code: 'no',
            price: 490,
            oldPrice: 980,
            labelPrice: 'крон',
            phoneHelper: 'Например +47 123456789',
            nameHelper: 'Екатерина Самойлова',
            nameError: 'Имя обязательно для заполнения',
            phoneError: 'Телефон обязателен для заполнения',
            emailError: 'E-mail incorrect',
            emailSuccess: 'Thanks, e-mail sended',
            countryError: 'Страна обязательна для заполнения'
        },
        pl: {
            name: 'Польша',
            code: 'pl',
            price: 159,
            oldPrice: 318,
            labelPrice: 'злот',
            phoneHelper: 'Например +48 123456789',
            nameHelper: 'Екатерина Самойлова',
            nameError: 'Имя обязательно для заполнения',
            phoneError: 'Телефон обязателен для заполнения',
            emailError: 'E-mail incorrect',
            emailSuccess: 'Thanks, e-mail sended',
            countryError: 'Страна обязательна для заполнения'
        },
        pt: {
            name: 'Португалия',
            code: 'pt',
            price: 49,
            oldPrice: 98,
            labelPrice: 'евро',
            phoneHelper: 'Например +351 123456789',
            nameHelper: 'Екатерина Самойлова',
            nameError: 'Имя обязательно для заполнения',
            phoneError: 'Телефон обязателен для заполнения',
            emailError: 'E-mail incorrect',
            emailSuccess: 'Thanks, e-mail sended',
            countryError: 'Страна обязательна для заполнения'
        },
        ro: {
            name: 'Румыния',
            code: 'ro',
            price: 149,
            oldPrice: 299,
            labelPrice: 'лей',
            phoneHelper: 'Например +40 123456789',
            nameHelper: 'Мария Ионеску',
            nameError: 'Имя обязательно для заполнения',
            phoneError: 'Телефон обязателен для заполнения',
            emailError: 'E-mail incorrect',
            emailSuccess: 'Thanks, e-mail sended',
            countryError: 'Страна обязательна для заполнения'
        },
        sk: {
            name: 'Словакия',
            code: 'sk',
            price: 39,
            oldPrice: 78,
            labelPrice: 'евро',
            phoneHelper: 'Например +421 12345678',
            nameHelper: 'Анна Мишкина',
            nameError: 'Имя обязательно для заполнения',
            phoneError: 'Телефон обязателен для заполнения',
            emailError: 'E-mail incorrect',
            emailSuccess: 'Thanks, e-mail sended',
            countryError: 'Страна обязательна для заполнения'
        },
        si: {
            name: 'Словения',
            code: 'sa',
            price: 39,
            oldPrice: 78,
            labelPrice: 'евро',
            phoneHelper: 'Например +386 12345678',
            nameHelper: 'Анна Мишкина',
            nameError: 'Имя обязательно для заполнения',
            phoneError: 'Телефон обязателен для заполнения',
            emailError: 'E-mail incorrect',
            emailSuccess: 'Thanks, e-mail sended',
            countryError: 'Страна обязательна для заполнения'
        },
		tr: {
            name: 'Турция',
            code: 'tr',
            price: 149,
            oldPrice: 298,
            labelPrice: 'лир',
            phoneHelper: 'Например +90 1234567890',
            nameHelper: 'Екатерина Самойлова',
            nameError: 'Имя обязательно для заполнения',
            phoneError: 'Телефон обязателен для заполнения',
            emailError: 'E-mail incorrect',
            emailSuccess: 'Thanks, e-mail sended',
            countryError: 'Страна обязательна для заполнения'
        },
        uz: {
            name: 'Узбекистан',
            code: 'uz',
            price: 119,
            oldPrice: 238,
            labelPrice: 'т.сум',
            phoneHelper: 'Например +998 123456789',
            nameHelper: 'Гультапчан Наркисова',
            nameError: 'Имя обязательно для заполнения',
            phoneError: 'Телефон обязателен для заполнения',
            emailError: 'E-mail incorrect',
            emailSuccess: 'Thanks, e-mail sended',
            countryError: 'Страна обязательна для заполнения'
        },
        ua: {
            name: 'Украина',
            code: 'ua',
            price: 450,
            oldPrice: 898,
            labelPrice: 'грн.',
            phoneHelper: 'Например +380 123456789',
            nameHelper: 'Анастасія Кравчук',
            nameError: 'Імя обовязково для заповнення',
            phoneError: 'Телефон обовязковий для заповнення',
            emailError: 'E-mail incorrect',
            emailSuccess: 'Thanks, e-mail sended',
            countryError: 'Країна обовязковий для заповнення'
        },
        
        fr: {
            name: 'Франция',
            code: 'fr',
            price: 39,
            oldPrice: 78,
            labelPrice: 'евро',
            phoneHelper: 'Например +33 123456789',
            nameHelper: 'Анна Мишкина',
            nameError: 'Имя обязательно для заполнения',
            phoneError: 'Телефон обязателен для заполнения',
            emailError: 'E-mail incorrect',
            emailSuccess: 'Thanks, e-mail sended',
            countryError: 'Страна обязательна для заполнения'
        },
        hr: {
            name: 'Хорватия',
            code: 'hr',
            price: 299,
            oldPrice: 598,
            labelPrice: 'кун',
            phoneHelper: 'Например +385 12345678',
            nameHelper: 'Екатерина Самойлова',
            nameError: 'Имя обязательно для заполнения',
            phoneError: 'Телефон обязателен для заполнения',
            emailError: 'E-mail incorrect',
            emailSuccess: 'Thanks, e-mail sended',
            countryError: 'Страна обязательна для заполнения'
        },
        cz: {
            name: 'Чехия',
            code: 'cz',
            price: 790,
            oldPrice: 1580,
            labelPrice: 'крон',
            phoneHelper: 'Например +420 123456789',
            nameHelper: 'Анна Мишкина',
            nameError: 'Имя обязательно для заполнения',
            phoneError: 'Телефон обязателен для заполнения',
            emailError: 'E-mail incorrect',
            emailSuccess: 'Thanks, e-mail sended',
            countryError: 'Страна обязательна для заполнения'
        },
        ch: {
            name: 'Швейцария',
            code: 'ch',
            price: 60,
            oldPrice: 120,
            labelPrice: 'фр.',
            phoneHelper: 'Например +41 123456789',
            nameHelper: 'Анна Мишкина',
            nameError: 'Имя обязательно для заполнения',
            phoneError: 'Телефон обязателен для заполнения',
            emailError: 'E-mail incorrect',
            emailSuccess: 'Thanks, e-mail sended',
            countryError: 'Страна обязательна для заполнения'
        },
        se: {
            name: 'Швеция',
            code: 'se',
            price: 490,
            oldPrice: 980,
            labelPrice: 'крон',
            phoneHelper: 'Например +46 123456789',
            nameHelper: 'Анна Мишкина',
            nameError: 'Имя обязательно для заполнения',
            phoneError: 'Телефон обязателен для заполнения',
            emailError: 'E-mail incorrect',
            emailSuccess: 'Thanks, e-mail sended',
            countryError: 'Страна обязательна для заполнения'
        },
        ee: {
            name: 'Эстония',
            code: 'ee',
            price: 39,
            oldPrice: 78,
            labelPrice: 'евро',
            phoneHelper: 'Например +372 12345678',
            nameHelper: 'София Йуримаа',
            nameError: 'Имя обязательно для заполнения',
            phoneError: 'Телефон обязателен для заполнения',
            emailError: 'E-mail incorrect',
            emailSuccess: 'Thanks, e-mail sended',
            countryError: 'Страна обязательна для заполнения'
        }
    };
})();